AllCops:
  NewCops: enable
  Exclude:
    - '*.md'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'db/schema.rb'
    - 'config/**/*.rb'
    - 'script/rails'
    - 'vendor/**/*'

Metrics/LineLength:
  Max: 130
  Exclude:
    - '*.gemspec'

Lint/UnusedBlockArgument:
  Exclude:
    - 'spec/tmp/**/*.rb'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/Documentation:
  Exclude:
    - 'db/migrate/*.rb'
    - 'spec/**/*.rb'

Gemspec/DevelopmentDependencies:
  EnforcedStyle: "gemspec"